### ISSUE TITLE
Kódlefedettség mérése és tesztek bővítése

### ISSUE THREAD

**Issue by spongyabazsi** [BME-MIT-IET/asdasd-iet-2020#2]
A kódlefedettség méréséhez a JaCoCo eszközt használtuk, ami a következő értéket mutatta:

![image](https://user-images.githubusercontent.com/47623529/82154634-792cea80-986f-11ea-8872-5c8ca006d844.png)

Ez az érték nem tűnik túl magasnak, azonban megvizsgálva a lefedett kódok halmazát, kijelenthető, hogy lényegi funkciókra történtek tesztelések.

Amit rendszeresen kihagytak a fejlesztők, azok az Exception-ök ellenőrzése bármilyen módon, tehát többek között ilyen unit teszteknek az elkészítése lesz a csapat feladata.

**Comment by codingbiro** [comment]
JaCoCo megfelelően került beállításra, minden az elvártak szerint működik.

**Comment by gombazsi** [comment]
Unit tesztek írásához először megpróbáltam a projekt fájljainak struktúrájából, és a kód olvasásából felderíteni a tesztelendő egységeket. Miután úgy éreztem, van egy elképzelésem arról, hogyan működnek együtt az osztályok, és mik az egyes felelősségek, átvizsgáltam a meglévő teszteseteket. Ezek alapján tisztább elképzelésem lett az uri -> template leképezés folyamatáról, és a meglévő unit teszteket fejlesztettem, egy fontos teszttel, mely az ontológiák import precedencia alapján történő választását ellenőrzi. A már meglévő tesztek végigkövetésénél feltűnt, hogy Clean Code szempontból elég komoly refaktorálást igényelne a projekt. A terminológiák kevererdése, és az azonos osztályhoz tartozó ugyanolyan nevű, de más felelősségű függvények (pl van olyan hívási lánc, ahol 4 egymást követő függvény neve megegyezik).  A unit tesztek írása helyett inkább a statikus tesztelés, manuális elemzés tűnt célravezetőnek, hiszen így jobban megismerhettem a kódot. Ezután megnéztem a SonarCloud felületen, mely kódrészletek nincsenek tesztelve.
5 olyan egységet találátam, ami még fedetlen volt, és értelme lenne tesztelni.
Ezen tesztek mindegyikében közös vol, hogy feleslegesen nagy számban függnek egymástól az egységek, nagyon nehéz megfelelő Unit teszteket írni, illetve objektum-orientált szempontból is sok kivetnivaló van (pl: protected getter publikus addparameter függvénybe csomagolása).
A Unit tesztek helyett tehát kézenfekvőbb lenne refaktorálásba energiát fektetni, és megtervezni a felsorolt szempontok alapján a projektet, megfelelő függőséginjekciót támogató keretrendszer használatával, amelyeken már lényegesen könnyebb Unit teszteket futtatni, és továbbfejlesztés szempontjából mindenképpen először hasznosabb lenne a kódon, mint a teszteseteken dolgozni.
A code coverage növelésének másik módszere lenne a tesztelt, de érvényre nem jutott sorokat ellenőrizni. Ezek azonban nagyon nagy részt getterek, setterek, konstruktorok, illetve hibakezelés (3 fájl pusztán az Exceptionök létrehozása). 

Úgy gondolom, a fejlesztés ezen szakaszában nem a Unit tesztek írása tehát a legkézenfekvőbb megoldás, ezért nagy számú tesztgyártás helyett statikus analízissel foglalkoztam, melynek eredménye, hogy a  program felépítését jelentősen át kellene dolgozni.
