### ISSUE TITLE
Exploratory Testing

### ISSUE THREAD

**Issue by codingbiro** [BME-MIT-IET/asdasd-iet-2020#4]
1. Dokumentációt használva az API hívások feltérképezése.
2. Egyes API-okhoz tartozó bemenetek, kimenetek, kivételek, kérések, válaszok és hívások vizsgálata.
3. Vizsgálat: API neve legyen egyértelmű és logikus, minimális paramétere legyen, létezésének oka.

**Comment by codingbiro** [comment]
**http://localhost:8080/ és http://localhost:8080/birthday endpointok tesztelése**

Különböző HTTP igékkel való tesztelés:
![Delete](https://user-images.githubusercontent.com/45095202/82729746-57fa4d00-9cfa-11ea-8299-f98e7a2067d9.png)

Input tesztelés:
![Get input](https://user-images.githubusercontent.com/45095202/82729747-592b7a00-9cfa-11ea-82c9-2205a330a070.png)

Különböző paraméterekkel való tesztelés:
![Get Params](https://user-images.githubusercontent.com/45095202/82729748-592b7a00-9cfa-11ea-9881-9a1d0c5528f0.png)

**Comment by spongyabazsi** [comment]
A tárgy Microsoft Team csatornájának [egy bejegyzése](https://www.ministryoftesting.com/dojo/lessons/exploratory-testing-an-api) alapján próbáltunk a könyvtártípusú (API) projektünkhöz melynek főleg a bemeneteit teszteltük, tekintettel arra, hogy a biztosított adathalmaz elég csekély. 

Az első képen látható az a teszt, ahol egy működő HTTP GET utasítást másféle igékkel küldünk az Atomgraphnak feldolgozásra. Mivel ez az ige nincs implementálva, a vártnak megfelelően az 501-es "Not implemented" hibakódot kaptunk,

A második képen látható az a teszt, ahol a query paramétereket ellenőrizzük. A sex paraméter a születésnaposok nemére utal, az általunk megadott "asdasd" paraméter pedig nem definiált nem a WikiDatában, ezért egy üres halmazt kapunk eredménynek.

A harmadik teszten az látható, hogy több query paramétert adunk meg. Az egyik közülük létező (sex), a másik pedig nincs definiálva. Ez a program futásában nem okoz gondot, a nem definiált paramétert figyelmen kívül hagyja, azonban a figyelmeztetést nem küld semmilyen formában, hogy hibás/nem létező paramétereket kapott, ez szülhet problémákat használat közben.

**Comment by gombazsi** [comment]
Mindent rendben találtam, szép munka
