### ISSUE TITLE
Performance/Load testing

### ISSUE THREAD

**Issue by kbszabolcs** [BME-MIT-IET/asdasd-iet-2020#5]
Ezen részfeladat célja a Performance/Load tesztelés **JMeter** segítségével.

A következő értékek szerint ítéljük meg a szoftver minőségét:

- Throughput: A szerver pillanatnyi áteresztőképessége, minél nagyobb az érték annál jobb.
- Average: Átlagos válaszidő.
- Deviation: Az átlagos válaszidőhöz képest az eltérés, minél kisebb az érték annál jobb.

**Comment by codingbiro** [comment]
JMeter Graph kimenete
![Graph](https://user-images.githubusercontent.com/45095202/82730748-6187b300-9d02-11ea-8b7e-0bca7824cafc.png)

Thread Group beállításai
![ThreadSettings](https://user-images.githubusercontent.com/45095202/82730749-62b8e000-9d02-11ea-9e33-b32397ddc620.png)

HTTP Request beállításai
![HttpSettings](https://user-images.githubusercontent.com/45095202/82730750-62b8e000-9d02-11ea-9617-23b625ad7001.png)

**Comment by codingbiro** [comment]
**Performance Testing paraméterrel:**

Sex paraméterrel:
![ParamSettings](https://user-images.githubusercontent.com/45095202/82731210-76b21100-9d05-11ea-844b-5c777748cf6b.png)

A graph:
![ParamGraph](https://user-images.githubusercontent.com/45095202/82731252-bb3dac80-9d05-11ea-8f0a-7143f54caa40.png)

**Comment by kbszabolcs** [comment]
> **Performance Testing:**
> 
> JMeter Graph kimenete
> ![Graph](https://user-images.githubusercontent.com/45095202/82730748-6187b300-9d02-11ea-8b7e-0bca7824cafc.png)
> 
> Thread Group beállításai
> ![ThreadSettings](https://user-images.githubusercontent.com/45095202/82730749-62b8e000-9d02-11ea-9e33-b32397ddc620.png)
> 
> HTTP Request beállításai
> ![HttpSettings](https://user-images.githubusercontent.com/45095202/82730750-62b8e000-9d02-11ea-9617-23b625ad7001.png)

**Comment by codingbiro** [comment]
**Load testing**

- 1500 user, 10-es looppal
- Sex paraméterrel

Graph:
![LoadTestGraph](https://user-images.githubusercontent.com/45095202/82731715-11601f00-9d09-11ea-86bc-e4a679c74de7.png)

**Comment by kbszabolcs** [comment]
Load testing során az 1500 felhasználó kéréseit már csak nagyon lassan tudta feldolgozni az alkalmazás. A Deviation 3-szorosa a Throughputnak, az átlagos válaszidő pedig irreálisan magas, több mint fél perc.

Konklúzióként levontuk, hogy ~100 felhasználóig jól teljesít az alkalmazás.

**Comment by spongyabazsi** [comment]
A feladat megoldása a megbeszélteknek megfelelően történt, a végrehajtás és a magyarázatok is helyesnek tűnnek.
