### ISSUE TITLE
Technológia fókusz

### ISSUE THREAD

**Issue by codingbiro** [BME-MIT-IET/asdasd-iet-2020#6]
- Build keretrendszer beüzemelése
- Deployment segítése

**Comment by codingbiro** [comment]
**Az alkalmazás környezetének beállítása**

Docker setup
![docker_setup](https://user-images.githubusercontent.com/45095202/82755698-9f094080-9dd5-11ea-965c-fe237e304588.png)

Docker Image segítségével érjük el a Processort
Ez a Docker Hubon elérhető
![docker_image](https://user-images.githubusercontent.com/45095202/82755746-eb548080-9dd5-11ea-88a8-6e6312ddf063.png)

Egy lokális SPARQL Service: a Fuseki futtatása
![fuseki_init](https://user-images.githubusercontent.com/45095202/82755771-1e970f80-9dd6-11ea-98d2-3fbb899e5871.png)

Fuseki a gyakorlatban: kérés és válasz
![fuseki_query](https://user-images.githubusercontent.com/45095202/82755787-3a021a80-9dd6-11ea-9cd7-d8ada6f8a575.png)

Saját ontológia és távoli SPARQL Service: futtatás
A Processor futtatása egy ontológiával (Wikidata)
![wikidata_init](https://user-images.githubusercontent.com/45095202/82755861-beed3400-9dd6-11ea-9377-dedd2430de51.png)

Most az alapértelmezett (root) útvonal helyett a birthdays route szerepel a példában, illetve paraméter is van
A kérés és kiszolgálása:
![wikidata_query](https://user-images.githubusercontent.com/45095202/82755931-2efbba00-9dd7-11ea-8e39-0d87c8ccb6e5.png)

**Comment by spongyabazsi** [comment]
## Build keretrendszer beüzemelése

A kezdő projektünkhöz kaptunk egy kiinduló pom.xml fájlt, ami arra utalt, hogy ezt Maven build keretrendszerhez lenne érdemes beüzemelni. Ennek voltak apróbb hiányosságai, például az, hogy a javax.annotation packaget nem akarta sehol megtalálni, ezért egy extra dependencyre volt szükségünk, valószínű valamilyen deprecation probléma lehetett.

Ezt utána a GitHub Continous Integration felületét, az Actionst használtuk ahhoz, hogy indítsunk egy workflowt. Ennek a legfőbb nehézsége az volt, hogy a projekt dokumentációjában nem találtuk, milyen Java verzióra lenne szükségünk, de ezt valamelyik fájl dependecy-jéből végül ki tudtuk olvasni.

Ezen felül, a Maven konfigurációban extra dependencyket és plugineket vettünk fel, amelyek lehetővé teszik pl. a SonarCloud, ami egy statikus ellenőrző eszköz, illetve a JaCoCo kódfedettség mérő eszköz használatát. A JaCoCo kimeneti fájlját feltöltjük a SonarCloud megfelelő repository-jába, ezzel egyszerűsítve munkánkat, hiszen egy felületen láthatjuk a fontosabb jellemzőket.

**Comment by kbszabolcs** [comment]
Dockeren a Fuseki példa futtatását láttam, a pom.xml is rendben. A szükséges eszközök beüzemelése az előre megbeszéltek szerint folyt.
